#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9
# bspc query --names -M
#bspc monitor -d 1 2 3 4 5
#bspc monitor DP-1 -d 6 7 8 9
#bspc monitor HDMI-1 -d 6 7 8 9

bspc config border_width 1
bspc config window_gap 8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config focused_border_color '#770000'
bspc config presel_feedback_color '#202020'
bspc config right_padding 0
bspc config left_padding 0
bspc config top_padding 0
bspc config bottom_padding 0

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

urxvt &
redshift -O 3200
